### ISSUE TITLE
Update ReadMe Correctly

### ISSUE THREAD

**Issue by developer-diganta** [developer-diganta/dbms-project#1]
Since there are 2 folders, it would be better to clear the npm i command. It would be helpful if is mentioned to cd into each folder and run npm init individually.

**Comment by surya-doc** [comment]
Hey, can you assign this to me?

**Comment by developer-diganta** [comment]
Yes sure! Go ahead!

**Comment by developer-diganta** [comment]
Feel free to ask for help if you need!

**Comment by surya-doc** [comment]
Ok sure.
